site_name: Robotics 12 Docs
site_url: http://ec2-35-90-176-80.us-west-2.compute.amazonaws.com
repo_url: https://github.com/Pablonara/rob12-2425
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - header.autohide
